Boom 💥 Failed to compile.
./src/App.js
Error: /Users/oscar/dev/test/styled-pnp/src/App.js: styled-components tried to access babel-plugin-macros, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: babel-plugin-macros (via "babel-plugin-macros")
Required by: styled-components@virtual:684a848f6513483ebac96fc1f63a175f2bd2f48c07909e7c125f8b73e0556de140bf56d727b6d784ed1353d9a023b9aeeeae52b80cb7986f99d5a056b062b968#npm:5.0.1 (via /Users/oscar/dev/test/styled-pnp/.yarn/$$virtual/styled-components-virtual-f4cd90d0ac/0/cache/styled-components-npm-5.0.1-87fcb612e6-2.zip/node_modules/styled-components/dist/)